name: MS2LDA_v2
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.11
  - ipython>=8.26.0
  - jupyterlab>=4.2.4
  - matplotlib>=3.9.1
  - seaborn>=0.13.2
  - pandas>=2.2.2
  - scipy>=1.10.1
  - networkx>=3.3
  - gensim>=4.3.3
  - psims>=1.3.3
  - pubchempy>=1.0.4
  - rdkit>=2023.9.4
  - pytest>=8.3.2
  - requests>=2.32.3
  - matchms>=0.27.0
  - numba>=0.57.1
  - llvmlite>=0.43.0
  - numpy==1.26.4
  - plotly>=5.23.0
  - pyarrow>=17.0.0
  - pymzml>=2.5.10
  - scikit-learn>=1.5.1
  - openpyxl=3.1.5
  - pip
  - pip:
      - dash>=2.18.1
      - dash_cytoscape>=1.0.2
      - dash_bootstrap_components>=1.6.0
      - tomotopy>=0.12.7
      - spec2vec>=0.8.0
      - PyQt6>=6.7.1
      - faiss-cpu==1.10.0

