name: MS2LDA_v2
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core runtime
  - python>=3.10,<3.13
  - matplotlib>=3.9.1
  - seaborn>=0.13.2
  - pandas>=2.2.2
  - scipy>=1.10.1
  - networkx>=3.3
  - gensim>=4.3.3
  - psims>=1.3.3
  - pubchempy>=1.0.4
  - pydantic=2.10.3
  - rdkit>=2023.9.6   # matches Poetry min; satisfies matchms
  - requests>=2.32.3
  - matchms>=0.27.0
  - plotly>=5.23.0
  - pyarrow>=17.0.0
  - pymzml>=2.5.10
  - scikit-learn>=1.5.1
  - openpyxl=3.1.5
  - diskcache>=5.6.3
  - dash-extensions==1.0.20

  # Optional / notebook tooling
  - ipython>=8.26.0
  - jupyterlab>=4.2.4

  # Development tools
  - black=24.3.0
  - flake8=7.0.0
  - mypy=1.10.0
  - pre-commit=3.7.0
  - pytest>=8.3.2
  - ruff>=0.11.0

  # Deployment tools
  - gunicorn>=23.0.0

  # Packages easier via pip (no conda recipe or bleeding-edge)
  - pip
  - pip:
      - dash>=2.18.1
      - dash_cytoscape>=1.0.2
      - dash_bootstrap_components>=1.6.0
      - tomotopy>=0.12.7
      - spec2vec>=0.8.0
      - PyQt6>=6.7.1
      - faiss-cpu==1.10.0
      - kaleido==0.2.1
      - git+https://github.com/j-a-dietrich/MassQueryLanguage4Mass2Motifs.git@ac1b10b1f020fdfde114c17d57f0ed9b435d9d47